# Generated by Django 6.0.5 on 2026-05-17 00:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='student_of_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
