# Generated by Django 6.0.5 on 2026-06-12 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_points_alter_assessment_max_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='content',
        ),
        migrations.AddField(
            model_name='contentblock',
            name='block_type',
            field=models.CharField(choices=[('file', 'Archivo Descargable'), (
                'page', 'Página de Contenido')], default='file', max_length=10),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='content_page',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contentblock',
            name='file',
            field=models.TextField(blank=True, null=True),
        ),
    ]
